// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package regmap_pkg;

    localparam REGMAP_DATA_WIDTH = 16;
    localparam REGMAP_MIN_ADDR_WIDTH = 4;

    typedef struct {
        logic [15:0] next;
    } regmap__dbg__CHIP_ID_H__ro_chip_id_h__in_t;

    typedef struct {
        regmap__dbg__CHIP_ID_H__ro_chip_id_h__in_t ro_chip_id_h;
    } regmap__dbg__CHIP_ID_H__in_t;

    typedef struct {
        logic [15:0] next;
    } regmap__dbg__CHIP_ID_ANA__ro_chip_id_ana__in_t;

    typedef struct {
        regmap__dbg__CHIP_ID_ANA__ro_chip_id_ana__in_t ro_chip_id_ana;
    } regmap__dbg__CHIP_ID_ANA__in_t;

    typedef struct {
        regmap__dbg__CHIP_ID_H__in_t CHIP_ID_H;
        regmap__dbg__CHIP_ID_ANA__in_t CHIP_ID_ANA;
    } regmap__dbg__in_t;

    typedef struct {
        regmap__dbg__in_t dbg;
    } regmap__in_t;

    typedef struct {
        logic [1:0] value;
    } regmap__dbg__rg_efuse_ctrl0__rg_efuse_1__out_t;

    typedef struct {
        logic swmod;
    } regmap__dbg__rg_efuse_ctrl0__rg_efuse_2__out_t;

    typedef struct {
        logic swmod;
    } regmap__dbg__rg_efuse_ctrl0__rg_efuse_3__out_t;

    typedef struct {
        logic [2:0] value;
    } regmap__dbg__rg_efuse_ctrl0__rg_efuse_4__out_t;

    typedef struct {
        logic [7:0] value;
    } regmap__dbg__rg_efuse_ctrl0__rg_efuse_5__out_t;

    typedef struct {
        regmap__dbg__rg_efuse_ctrl0__rg_efuse_1__out_t rg_efuse_1;
        regmap__dbg__rg_efuse_ctrl0__rg_efuse_2__out_t rg_efuse_2;
        regmap__dbg__rg_efuse_ctrl0__rg_efuse_3__out_t rg_efuse_3;
        regmap__dbg__rg_efuse_ctrl0__rg_efuse_4__out_t rg_efuse_4;
        regmap__dbg__rg_efuse_ctrl0__rg_efuse_5__out_t rg_efuse_5;
    } regmap__dbg__rg_efuse_ctrl0__out_t;

    typedef struct {
        logic [1:0] value;
    } regmap__dbg__rg_error__rg_efuse_10__out_t;

    typedef struct {
        logic value;
    } regmap__dbg__rg_error__rg_err_addr_overlap__out_t;

    typedef struct {
        logic value;
    } regmap__dbg__rg_error__rg_err_addr_flip__out_t;

    typedef struct {
        regmap__dbg__rg_error__rg_efuse_10__out_t rg_efuse_10;
        regmap__dbg__rg_error__rg_err_addr_overlap__out_t rg_err_addr_overlap;
        regmap__dbg__rg_error__rg_err_addr_flip__out_t rg_err_addr_flip;
    } regmap__dbg__rg_error__out_t;

    typedef struct {
        regmap__dbg__rg_efuse_ctrl0__out_t rg_efuse_ctrl0;
        regmap__dbg__rg_error__out_t rg_error;
    } regmap__dbg__out_t;

    typedef struct {
        regmap__dbg__out_t dbg;
    } regmap__out_t;
endpackage
