// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module regmap (
        input wire clk,
        input wire arst_n,

        input wire s_cpuif_req,
        input wire s_cpuif_req_is_wr,
        input wire [3:0] s_cpuif_addr,
        input wire [15:0] s_cpuif_wr_data,
        input wire [15:0] s_cpuif_wr_biten,
        output wire s_cpuif_req_stall_wr,
        output wire s_cpuif_req_stall_rd,
        output wire s_cpuif_rd_ack,
        output wire s_cpuif_rd_err,
        output wire [15:0] s_cpuif_rd_data,
        output wire s_cpuif_wr_ack,
        output wire s_cpuif_wr_err,

        input regmap_pkg::regmap__in_t hwif_in,
        output regmap_pkg::regmap__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [3:0] cpuif_addr;
    logic [15:0] cpuif_wr_data;
    logic [15:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [15:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    assign cpuif_req = s_cpuif_req;
    assign cpuif_req_is_wr = s_cpuif_req_is_wr;
    assign cpuif_addr = s_cpuif_addr;
    assign cpuif_wr_data = s_cpuif_wr_data;
    assign cpuif_wr_biten = s_cpuif_wr_biten;
    assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
    assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
    assign s_cpuif_rd_ack = cpuif_rd_ack;
    assign s_cpuif_rd_err = cpuif_rd_err;
    assign s_cpuif_rd_data = cpuif_rd_data;
    assign s_cpuif_wr_ack = cpuif_wr_ack;
    assign s_cpuif_wr_err = cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            logic CHIP_ID_H;
            logic CHIP_ID_ANA;
            logic rg_efuse_ctrl0;
            logic rg_error;
        } dbg;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [15:0] decoded_wr_data;
    logic [15:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.dbg.CHIP_ID_H = cpuif_req_masked & (cpuif_addr == 4'h0);
        decoded_reg_strb.dbg.CHIP_ID_ANA = cpuif_req_masked & (cpuif_addr == 4'h4);
        decoded_reg_strb.dbg.rg_efuse_ctrl0 = cpuif_req_masked & (cpuif_addr == 4'h6);
        decoded_reg_strb.dbg.rg_error = cpuif_req_masked & (cpuif_addr == 4'he);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                struct {
                    logic [1:0] next;
                    logic load_next;
                } rg_efuse_1;
                struct {
                    logic [2:0] next;
                    logic load_next;
                } rg_efuse_4;
                struct {
                    logic [7:0] next;
                    logic load_next;
                } rg_efuse_5;
            } rg_efuse_ctrl0;
            struct {
                struct {
                    logic [1:0] next;
                    logic load_next;
                } rg_efuse_10;
                struct {
                    logic next;
                    logic load_next;
                } rg_err_addr_overlap;
                struct {
                    logic next;
                    logic load_next;
                } rg_err_addr_flip;
            } rg_error;
        } dbg;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                struct {
                    logic [1:0] value;
                } rg_efuse_1;
                struct {
                    logic [2:0] value;
                } rg_efuse_4;
                struct {
                    logic [7:0] value;
                } rg_efuse_5;
            } rg_efuse_ctrl0;
            struct {
                struct {
                    logic [1:0] value;
                } rg_efuse_10;
                struct {
                    logic value;
                } rg_err_addr_overlap;
                struct {
                    logic value;
                } rg_err_addr_flip;
            } rg_error;
        } dbg;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: regmap.dbg.rg_efuse_ctrl0.rg_efuse_1
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.dbg.rg_efuse_ctrl0.rg_efuse_1.value;
        load_next_c = '0;
        if(decoded_reg_strb.dbg.rg_efuse_ctrl0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.dbg.rg_efuse_ctrl0.rg_efuse_1.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.dbg.rg_efuse_ctrl0.rg_efuse_1.next = next_c;
        field_combo.dbg.rg_efuse_ctrl0.rg_efuse_1.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.dbg.rg_efuse_ctrl0.rg_efuse_1.value <= 2'h2;
        end else if(field_combo.dbg.rg_efuse_ctrl0.rg_efuse_1.load_next) begin
            field_storage.dbg.rg_efuse_ctrl0.rg_efuse_1.value <= field_combo.dbg.rg_efuse_ctrl0.rg_efuse_1.next;
        end
    end
    assign hwif_out.dbg.rg_efuse_ctrl0.rg_efuse_1.value = field_storage.dbg.rg_efuse_ctrl0.rg_efuse_1.value;
    assign hwif_out.dbg.rg_efuse_ctrl0.rg_efuse_2.swmod = decoded_reg_strb.dbg.rg_efuse_ctrl0 && decoded_req_is_wr;
    assign hwif_out.dbg.rg_efuse_ctrl0.rg_efuse_3.swmod = decoded_reg_strb.dbg.rg_efuse_ctrl0 && decoded_req_is_wr;
    // Field: regmap.dbg.rg_efuse_ctrl0.rg_efuse_4
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.dbg.rg_efuse_ctrl0.rg_efuse_4.value;
        load_next_c = '0;
        if(decoded_reg_strb.dbg.rg_efuse_ctrl0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.dbg.rg_efuse_ctrl0.rg_efuse_4.value & ~decoded_wr_biten[7:5]) | (decoded_wr_data[7:5] & decoded_wr_biten[7:5]);
            load_next_c = '1;
        end
        field_combo.dbg.rg_efuse_ctrl0.rg_efuse_4.next = next_c;
        field_combo.dbg.rg_efuse_ctrl0.rg_efuse_4.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.dbg.rg_efuse_ctrl0.rg_efuse_4.value <= 3'h0;
        end else if(field_combo.dbg.rg_efuse_ctrl0.rg_efuse_4.load_next) begin
            field_storage.dbg.rg_efuse_ctrl0.rg_efuse_4.value <= field_combo.dbg.rg_efuse_ctrl0.rg_efuse_4.next;
        end
    end
    assign hwif_out.dbg.rg_efuse_ctrl0.rg_efuse_4.value = field_storage.dbg.rg_efuse_ctrl0.rg_efuse_4.value;
    // Field: regmap.dbg.rg_efuse_ctrl0.rg_efuse_5
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.dbg.rg_efuse_ctrl0.rg_efuse_5.value;
        load_next_c = '0;
        if(decoded_reg_strb.dbg.rg_efuse_ctrl0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.dbg.rg_efuse_ctrl0.rg_efuse_5.value & ~decoded_wr_biten[15:8]) | (decoded_wr_data[15:8] & decoded_wr_biten[15:8]);
            load_next_c = '1;
        end
        field_combo.dbg.rg_efuse_ctrl0.rg_efuse_5.next = next_c;
        field_combo.dbg.rg_efuse_ctrl0.rg_efuse_5.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.dbg.rg_efuse_ctrl0.rg_efuse_5.value <= 8'h0;
        end else if(field_combo.dbg.rg_efuse_ctrl0.rg_efuse_5.load_next) begin
            field_storage.dbg.rg_efuse_ctrl0.rg_efuse_5.value <= field_combo.dbg.rg_efuse_ctrl0.rg_efuse_5.next;
        end
    end
    assign hwif_out.dbg.rg_efuse_ctrl0.rg_efuse_5.value = field_storage.dbg.rg_efuse_ctrl0.rg_efuse_5.value;
    // Field: regmap.dbg.rg_error.rg_efuse_10
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.dbg.rg_error.rg_efuse_10.value;
        load_next_c = '0;
        if(decoded_reg_strb.dbg.rg_error && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.dbg.rg_error.rg_efuse_10.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.dbg.rg_error.rg_efuse_10.next = next_c;
        field_combo.dbg.rg_error.rg_efuse_10.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.dbg.rg_error.rg_efuse_10.value <= 2'h2;
        end else if(field_combo.dbg.rg_error.rg_efuse_10.load_next) begin
            field_storage.dbg.rg_error.rg_efuse_10.value <= field_combo.dbg.rg_error.rg_efuse_10.next;
        end
    end
    assign hwif_out.dbg.rg_error.rg_efuse_10.value = field_storage.dbg.rg_error.rg_efuse_10.value;
    // Field: regmap.dbg.rg_error.rg_err_addr_overlap
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.dbg.rg_error.rg_err_addr_overlap.value;
        load_next_c = '0;
        if(decoded_reg_strb.dbg.rg_error && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.dbg.rg_error.rg_err_addr_overlap.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end
        field_combo.dbg.rg_error.rg_err_addr_overlap.next = next_c;
        field_combo.dbg.rg_error.rg_err_addr_overlap.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.dbg.rg_error.rg_err_addr_overlap.value <= 1'h1;
        end else if(field_combo.dbg.rg_error.rg_err_addr_overlap.load_next) begin
            field_storage.dbg.rg_error.rg_err_addr_overlap.value <= field_combo.dbg.rg_error.rg_err_addr_overlap.next;
        end
    end
    assign hwif_out.dbg.rg_error.rg_err_addr_overlap.value = field_storage.dbg.rg_error.rg_err_addr_overlap.value;
    // Field: regmap.dbg.rg_error.rg_err_addr_flip
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.dbg.rg_error.rg_err_addr_flip.value;
        load_next_c = '0;
        if(decoded_reg_strb.dbg.rg_error && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.dbg.rg_error.rg_err_addr_flip.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end
        field_combo.dbg.rg_error.rg_err_addr_flip.next = next_c;
        field_combo.dbg.rg_error.rg_err_addr_flip.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.dbg.rg_error.rg_err_addr_flip.value <= 1'h1;
        end else if(field_combo.dbg.rg_error.rg_err_addr_flip.load_next) begin
            field_storage.dbg.rg_error.rg_err_addr_flip.value <= field_combo.dbg.rg_error.rg_err_addr_flip.next;
        end
    end
    assign hwif_out.dbg.rg_error.rg_err_addr_flip.value = field_storage.dbg.rg_error.rg_err_addr_flip.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [15:0] readback_data;

    // Assign readback values to a flattened array
    logic [15:0] readback_array[4];
    assign readback_array[0][15:0] = (decoded_reg_strb.dbg.CHIP_ID_H && !decoded_req_is_wr) ? hwif_in.dbg.CHIP_ID_H.ro_chip_id_h.next : '0;
    assign readback_array[1][15:0] = (decoded_reg_strb.dbg.CHIP_ID_ANA && !decoded_req_is_wr) ? hwif_in.dbg.CHIP_ID_ANA.ro_chip_id_ana.next : '0;
    assign readback_array[2][1:0] = (decoded_reg_strb.dbg.rg_efuse_ctrl0 && !decoded_req_is_wr) ? field_storage.dbg.rg_efuse_ctrl0.rg_efuse_1.value : '0;
    assign readback_array[2][4:2] = '0;
    assign readback_array[2][7:5] = (decoded_reg_strb.dbg.rg_efuse_ctrl0 && !decoded_req_is_wr) ? field_storage.dbg.rg_efuse_ctrl0.rg_efuse_4.value : '0;
    assign readback_array[2][15:8] = (decoded_reg_strb.dbg.rg_efuse_ctrl0 && !decoded_req_is_wr) ? field_storage.dbg.rg_efuse_ctrl0.rg_efuse_5.value : '0;
    assign readback_array[3][1:0] = (decoded_reg_strb.dbg.rg_error && !decoded_req_is_wr) ? field_storage.dbg.rg_error.rg_efuse_10.value : '0;
    assign readback_array[3][2:2] = (decoded_reg_strb.dbg.rg_error && !decoded_req_is_wr) ? field_storage.dbg.rg_error.rg_err_addr_overlap.value : '0;
    assign readback_array[3][3:3] = (decoded_reg_strb.dbg.rg_error && !decoded_req_is_wr) ? field_storage.dbg.rg_error.rg_err_addr_flip.value : '0;
    assign readback_array[3][15:4] = '0;

    // Reduce the array
    always_comb begin
        automatic logic [15:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<4; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
